### ISSUE TITLE
Unsafe Language used in Commit Message

### ISSUE THREAD

**Issue by Fabhi** [stupendoussuperpowers/media-tracker#1]
Dear Developer

You are using NSFW language in your commit messages like :
 **Might be the last straw, lads, added redis login with db but VUE FUCKING JS IS BEING SHITTY AF WHO DESIGNS A FRAMEWORK LIKE THIS** .
Please refrain from this, otherwise your repository will be put under **Watch** so that we are informed when you post such nice messages.
Thank you

**Comment by stupendoussuperpowers** [comment]
Really sorry that about this slip up, and thanks for bringing it to our attention. 

We've reviewed the commit and the message and the time it went up, and it appears that it was a lashing out due to those conditions.

I am marking this issue as closed.
